@echo off
echo [INFO] Starting Maven installation...
echo [INFO] Setting PowerShell execution policy...
powershell -Command "Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser -Force"
echo [INFO] Installing Scoop package manager...
powershell -Command "Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression"
echo [INFO] Installing Maven using Scoop...
powershell -Command "scoop install main/maven"
echo [INFO] Maven installation completed!
echo [INFO] Please restart the command prompt to use Maven.
pause